---
- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- name: Ensure Apache is installed.
  package:
    name: "{{ apache_packages }}"
    state: "present"

- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "httpd"
    state: "started"
    enabled: true


- name: POST contents
  uri:
    url: http://116.202.8.134/wp-admin/install.php?step=2
    method: POST
    body_format: form-urlencoded
    body:
    - [ weblog_title, "{{WP_DOMAIN}}" ]
    - [ user_name, "{{WP_ADMIN_USERNAME}}" ]
    - [ admin_email, "{{WP_ADMIN_EMAIL}}" ]
    - [ admin_password, "{{WP_ADMIN_PASSWORD}}" ]
    - [ admin_password2, "{{WP_ADMIN_PASSWORD}}" ] 
    - [ pw_weak, 1 ]
    - [ blog_public, 0 ]

