#Task to install php packages
---

- name: install remi71 repo
  command: 
    - wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm && rpm -Uvh remi-release-7.rpm && rm -f remi-release-7.rpm


- name: Enable remi repo for PHP 71.
  set_fact: php_enablerepo="base,remi-php71,remi,epel,updates"
  set_fact: php_disablerepo="*"
  when: php_version == "71"

- name: Install PHP Packages
  yum:
    name: 
    - php
    - php-common
    - php-cli
    - php-fpm
    - php-pgsql
    - php-mysqlnd
    - php-gd
    - php-bz2
    - php-zip
    - php-json
    - php-xml
    - php-curl
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-bcmath
    - php-soap
    - php-opcache
    - php-pdo
  state: present

- name: Set PHP memory limit to 512MB
  lineinfile:
    path: /etc/php.ini
    regexp: '^memory_limit ='
    line: memory_limit = 512M
