#Task to install php packages
---

- name: Install PHP Packages
  yum:
    name: 
    - php
    - php-common
    - php-cli
    - php-fpm
    - php-pgsql
    - php-mysqlnd
    - php-gd
    - php-bz2
    - php-zip
    - php-json
    - php-xml
    - php-curl
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-soap
    - php-opcache
    - php-pdo
# state: present

- name: Set PHP memory limit to 256MB
  lineinfile:
    path: /etc/php.ini
    regexp: '^memory_limit ='
    line: memory_limit = 256M
