---

- name: Copy error message into wrongdocumentroot
  template:
    src: templates/wrongdocroot_index.html
    dest: /var/www/html/index.html

- name: Commenting the correct documentroot line
  replace:
    path: /etc/httpd/conf.d/vhosts.conf
    regexp: '(.*DocumentRoot "/var/www/vhosts/demo.com".*)'
    replace: '#\1'

- name: Uncommentiong the incorrect documentroot line
  replace:
    path: /etc/httpd/conf.d/vhosts.conf
    regexp: '^#(.*/var/www/html.*)'
    replace: '\1'

- name: Have apache listen in on port 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: Listen 80
    line: Listen 8080

- name: Restart apache to break the website
  service:
    name: httpd
    state: restarted
